name: dart2native
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

# Add the bin/dart2native.dart script to the scripts pub installs.
executables:
  dart2native:

dependencies:
   path: any

dev_dependencies:
  lints: any
