name: analyzer_cli
description: Command line interface for the Dart Analyzer.

# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: "^2.14.0"

dependencies:
  analyzer: any
  args: any
  linter: ^1.0.0
  meta: any
  path: any
  pub_semver: ^2.0.0
  yaml: any

dev_dependencies:
  lints: any
  test_reflective_loader: ^0.2.0
  test: ^1.0.0

dependency_overrides:
  analyzer:
    path: ../analyzer
  meta:
    path: ../meta
