name: nnbd_migration

# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  _fe_analyzer_shared: any
  analyzer: any
  analyzer_plugin: any
  args: ^2.3.0
  charcode: ^1.1.0
  cli_util: ^0.3.5
  collection: ^1.15.0
  crypto: ^3.0.1
  meta: any
  path: ^1.6.2
  pub_semver: ^2.1.0
  source_span: ^1.4.1
  yaml: any

dev_dependencies:
  analyzer_utilities:
    path: ../analyzer_utilities
  http: ^0.13.4
  pedantic: ^1.9.0
  test: ^1.6.4
  test_reflective_loader: ^0.2.0

dependency_overrides:
  _fe_analyzer_shared:
    path: ../_fe_analyzer_shared
  analyzer:
    path: ../analyzer
  analyzer_plugin:
    path: ../analyzer_plugin
  meta:
    path: ../meta
